accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from . import forms

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html', form_class=forms.MyLoginForm),name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('my-profile/', views.account_detail, name='detail'),
    path('my-profile/delete/', views.delete_account, name='delete'),
]

mubm/urls.py
from django.contrib import admin
from django.urls import re_path, path, include
from . import views
from records import ajax_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('test/', views.TestPage.as_view(),name='test'),
    path('thanks/', views.ThanksPage.as_view(), name='thanks'),
    path('projects/', include('projects.urls', namespace='projects')),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import (User,
                                        PermissionsMixin)
# Create your models here.


class User(User, PermissionsMixin):
    """
    Extending the user model
    """
    def __str__(self):
        """
        String representation
        """
        return self.first_name + ' ' + self.last_name

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from material import Layout, Row, Fieldset
from django import forms


class MyLoginForm(AuthenticationForm):
    """
    This form class handles the authentication
    """
    def __init__(self, *args, **kwargs):
        super(MyLoginForm, self).__init__(*args, **kwargs)
        self.fields['username'].label = 'Email'



class UserCreateForm(UserCreationForm):
    """
    This form class handles the sign up
    """

    class Meta:
        fields = ('first_name', 'last_name', 'email', 'password1','password2')
        model = get_user_model()


    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        # some additional customization
        for fieldname in ['first_name', 'last_name', 'email']:
            self.fields[fieldname].required = True
        for fieldname in ['password1', 'password2']:
            self.fields[fieldname].help_text = None
        self.fields['email'].error_messages = "Please provide a valid email address"

    def save(self, commit=True):
        user = super(UserCreateForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        user.username = user.email
        if commit:
            user.save()
        return user

    layout = Layout(Row('first_name', 'last_name'),
                    'email',
                    Row('password1', 'password2'))

accounts/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic
from . import forms
from django.forms.models import model_to_dict
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
User = get_user_model()


class SignUp(generic.CreateView):
    """
    Class based view, sign up page
    """

    form_class = forms.UserCreateForm

    success_url = reverse_lazy('login')

    template_name = 'accounts/signup.html'

@login_required
def account_detail(request):
    """
    Account detail page
    """
    u = request.user
    data = forms.UserCreateForm(data=model_to_dict(u))

    context = {
        'user':u,
        'data':data
    }
    template_name = 'accounts/account_detail.html'

    return render(request, template_name, context)

@login_required
def delete_account(request):
    """
    Delete account 
    """
    u = request.user
    u.delete()

    return redirect('thanks')

accounts/templates/accounts/account_detail.html
{% extends "base.html" %}
{% load static %}

{% block breadcrumb %}
  <a href="{% url 'accounts:detail' %}" class="breadcrumb">My Profile</a>
{% endblock %}
{% block content %}


<div class="row">
  <div class="col s12">
    <div class="card grey lighten-5">
      <div class="card-content">
        <div class="row">
          <div class="col s12">

              <div class="row">

                <div class="col s6 offset-s3">
                  <img class="circle responsive-img" src="{% static 'images/usericon.svg' %}" alt="">



                  <h2 class="center">{{ user.first_name }} {{ user.last_name }}</h2>
                  <h4 class="center">{{ user.email}}</h4>
                </div>
              </div>
          </div>
        </div>
        <div class="card-action">
          <div class="right-align">
            <a class="btn waves-effect btn-medium waves-light red darken-3" href="#delete_acc">
              <i class="material-icons left">delete</i>
              delete account
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div id="delete_acc" class="modal">
   <div class="modal-content">
     <h4 class="center-align">Are you sure you want to delete your account?</h4>
     <p class="center-align">By doing so you will no longer have access to your projects.
   </div>
   <div class="modal-footer">
     <div class="modal-action right-align">
       <a href="#!" class="modal-close btn-flat waves-effect waves-blue grey-text">Cancel</a>
       <a href="{% url 'accounts:delete' %}" class="modal-close btn-flat waves-effect waves-red blue-grey-text">Delete Account</a>

     </div>
   </div>
 </div>
 <script type="text/javascript" src="{% static 'js/modal.js' %}"></script>
{% endblock %}

accounts/templates/accounts/login.html
{% extends "base.html" %}


{% block content_account %}
<br>
<div class="row">
  <div class="col l8 m8 s12 offset-l2 offset-m2">
    <div class="card">
      <div class="card-content">
        <span class="card-title"><h1 class="center-align">Log In</h1></span>
        <h4 class="center-align hide-on-med-and-down">Fill in your email and password to Log in. <br>
                                Not yet a member? <a href="{% url 'accounts:signup' %}">Sign Up</a> now!</h4>
        <br>
        <form method="POST">
          {% csrf_token %}
          {% form %}
          {% part form.username prefix %}<i class="material-icons prefix">account_circle</i>{% endpart %}
          {% part form.password prefix %}<i class="material-icons prefix">lock_outline</i>{% endpart %}
          {% endform %}
          <div class="center-align">
            <button type="submit" name="_submit" class="btn btn-large center waves waves-effect indigo">Log In</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}

accounts/templates/accounts/signup.html
{% extends "base.html" %}


{% block content_account %}
<br>
<div class="row">
  <div class="col l8 m8 s12 offset-l2 offset-m2">
    <div class="card">
      <div class="card-content">
        <span class="card-title"><h1 class="center-align">Sign Up</h1></span>
        <h4 class="center-align hide-on-med-and-down">Fill in the form below to register. <br>
                                Already a member? <a href="{% url 'accounts:login' %}">Log in</a> instead!</h4>
            <br>
        <form class="viewform" method="POST">
          {% csrf_token %}
          {% form form=form %} {% endform %}
          <br>
          <div class="center-align">
            <button type="submit" name="_submit" class="btn btn-large center waves waves-effect indigo">Sign Up</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}