mubm/urls.py
from django.contrib import admin
from django.urls import re_path, path, include
from . import views
from records import ajax_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('test/', views.TestPage.as_view(),name='test'),
    path('thanks/', views.ThanksPage.as_view(), name='thanks'),
    path('projects/', include('projects.urls', namespace='projects')),
]

projects/urls.py
from django.urls import path, re_path, include
from . import views

app_name = 'projects'


urlpatterns = [
    path('', views.list_projects, name='all'),
    path('new/', views.create_project ,name='create'),
    path('<slug:slug>/records/', include('records.urls', namespace='records')),
    path('<slug:slug>/', views.project_detail, name='single'),
    path('<slug:slug>/leave/', views.LeaveProject.as_view(),name='leave'),
    path('<slug:slug>/invite/', views.project_invite ,name='invite'),
    path('<slug:slug>/delete/', views.delete_project, name='delete'),
    path('<slug:slug>/settings/', views.project_settings, name='settings'),
    path('<slug:slug>/settings/update', views.edit_project_settings, name='edit'),
    path('<slug:slug>/accept-invite/', views.JoinProject.as_view(), name='accept'),
    path('<slug:slug>/decline-invite/', views.DeclineInvite.as_view(), name='decline'),
    path('<slug:slug>/withdraw-invite/<int:pk>', views.delete_invite, name='withdraw'),
    path('<slug:slug>/delete-member/<int:pk>', views.delete_member, name='delete-member'),
    path('<slug:slug>/import/', views.project_import_file, name='import'),
    path('<slug:slug>/export/', views.project_export_file, name='export'),
    path('<slug:slug>/<int:pk>/edit-perm/', views.edit_project_member, name='editperm'),

]

projects/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse
from django.contrib.auth import get_user_model
from django import template
User = get_user_model()
register = template.Library()




class Project(models.Model):
    project_title = models.CharField(max_length=200)
    description = models.TextField(max_length=500, blank=True)

    # This slug should be edited to allow for projects with the same name.
    slug = models.SlugField(allow_unicode=True, unique=True)

    # A project can have many members, and users can be members of many projects.
    members = models.ManyToManyField(User, through="ProjectMember")



    def __str__(self):
        return self.project_title

    def save(self, *args, **kwargs):
        if Project.objects.all().count() == 0: # in case it is the first project ever created.
            i = 1
        else:
            i = Project.objects.latest('pk').pk + 1
        while Project.objects.filter(slug=slugify(self.project_title + str(i))).count() != 0:
            i = i + 1
        self.slug = slugify(self.project_title + str(i))
        super().save(*args,**kwargs)

    def get_absolute_url(self):
        return reverse('projects:single',kwargs={'slug':self.slug})

    class Meta:
        ordering = ['project_title']

class ProjectMember(models.Model):
    """
    This project member class allows for further customization and access control
    """
    project = models.ForeignKey(Project, related_name='memberships', on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='user_projects', on_delete=models.CASCADE)
    is_owner = models.BooleanField(default=False)
    is_editor = models.BooleanField(default=False)
    is_reader = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ('project', 'user')


class Invitation(models.Model):
    """
    This model stores the invitation that can either be declined (deleted) or,
    if accepted, the information stored here can be used to define a new membership
    """
    project = models.ForeignKey(Project, related_name='invites', on_delete=models.CASCADE)
    sender = models.ForeignKey(User, related_name='user_invites_sent', on_delete=models.CASCADE)
    reciever = models.ForeignKey(User, related_name='user_invites_recieved', on_delete=models.CASCADE)
    message = models.TextField(max_length=500)
    is_owner = models.BooleanField(default=False)
    is_editor = models.BooleanField(default=False)
    is_reader = models.BooleanField(default=False)
    def __str__(self):
        return self.project.project_title + ' invitation from '+ self.sender.first_name + ' to ' + self.reciever.first_name

projects/forms.py
from django import forms
from . import models
from django.core.exceptions import ObjectDoesNotExist, ValidationError
from django.utils.text import slugify
from django.contrib.auth import get_user_model
User = get_user_model()

class CreateProjectForm(forms.ModelForm):
    """
    This form class handles the creation of a new project
    """
    class Meta:
        model = models.Project
        fields = ['project_title', 'description']
    # This was initially implemented to ensure users dont create projects with
    # the same slug. This has been changed in projects/models.py and is no
    # longer needed    
    # def clean(self):
    #     cleaned_data = super(CreateProjectForm, self).clean()
    #     title = cleaned_data.get('project_title')
    #     try:
    #         slug = slugify(title)
    #         models.Project.objects.get(slug=slug)
    #         raise forms.ValidationError("Sorry, that projecttitle is already in use")
    #     except ObjectDoesNotExist:
    #         pass

class ImportFileForm(forms.Form):
    """
    Simple file input form for the import file functionality
    """
    file = forms.FileInput()

class ProjectMemberForm(forms.Form):
    """
    This form allows an admin to change the project members' permissions
    """
    PERM_CHOICES = (
        ('is_owner','Admin'),
        ('is_editor','Read&Write'),
        ('is_reader','ReadOnly'),
    )
    permission = forms.ChoiceField(label="Permission", choices=PERM_CHOICES)


class InviteForm(forms.Form):
    """
    This fowm allows a project admin to invite other users
    """
    PERM_CHOICES = (
        ('is_owner','Admin'),
        ('is_editor','Read&Write'),
        ('is_reader','ReadOnly'),
    )
    email = forms.EmailField(label="Send an invitation by entering your collegue's Email")
    message = forms.CharField(label="Message", required=False)
    permission = forms.ChoiceField(label="Permission", choices=PERM_CHOICES)

    def __init__(self, *args, **kwargs):
        self.project = kwargs.pop('project')
        super(InviteForm, self).__init__(*args,**kwargs)

    def clean(self):
        """
        Overwriting the clean method to add in extra validation
        """
        cleaned_data = super(InviteForm, self).clean()
        email = cleaned_data.get('email')
        message = cleaned_data.get('message')
        try:
            User.objects.get(email=email)
        except ObjectDoesNotExist:
            raise forms.ValidationError('No user with email ' + email + ' exists' )

        try:
            models.ProjectMember.objects.get(user=User.objects.get(email=email), project=self.project)
            raise forms.ValidationError('User is already a member!')
        except ObjectDoesNotExist:
            pass

        try:
            models.Invitation.objects.get(reciever=User.objects.get(email=email), project=self.project)
            raise forms.ValidationError('User is already invited!')
        except ObjectDoesNotExist:
            pass

projects/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import generic
from projects.models import Project, ProjectMember, Invitation
from records.models import Record
from django.shortcuts import get_object_or_404
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.files.storage import FileSystemStorage
from django.forms.models import model_to_dict
from . import forms
from datetime import datetime
import bibtexparser
from bibtexparser.bibdatabase import BibDatabase
from pylatexenc.latex2text import LatexNodes2Text
from pylatexenc.latexencode import utf8tolatex
import os
from django.conf import settings
from django.http import HttpResponse
from records import data
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
User = get_user_model()

"""
This is projects/views.py

This file contains the views related to a project
"""


@login_required
def create_project(request):
    """
    This view allows a user to create a new project
    """
    form = forms.CreateProjectForm(request.POST or None)
    template = 'projects/project_form.html'
    context = {
        'form':form,
    }

    if request.method == 'POST':
        if form.is_valid():
            project = form.save()
            user = request.user
            pm = ProjectMember.objects.get_or_create(project=project, user=user, is_owner=True)[0]
            pm.save()
            return redirect('projects:single', slug=project.slug)
    return render(request, template, context)

@login_required
def project_detail(request, slug):
    """
    This view is availible to all project members
    This view contains the overview of a project including
    the datatable with all the records
    """
    # Try except to make sure the user is a member of this project
    try:
        ProjectMember.objects.get(user=request.user, project=Project.objects.get(slug=slug))
    except ObjectDoesNotExist:
        # User is not a member
        return HttpResponse("You're trying to access a project you're not a member of or a project that does not exist.")
    else:
        # User is a member, details are provided and template is rendered.
        project = get_object_or_404(Project, slug=slug)
        records = Record.objects.filter(project=project)
        # If the project contains duplicates they are included in the response.
        duplicates = []
        for record in records:
            if records.filter(cite_key=record.cite_key).count() > 1:
                duplicates.append(record)

        context = {
            'project':project,
            'userperm':project.memberships.get(user=request.user),
            'duplicates':duplicates,
            }
        template = 'projects/project_detail.html'
        return render(request, template, context)

@login_required
def project_settings(request, slug):
    """
    All members can access this view
    """
    # Try except to make sure the user is a member of this project
    try:
        ProjectMember.objects.get(user=request.user, project=Project.objects.get(slug=slug))
    except ObjectDoesNotExist:
        # User is not a member
        return HttpResponse("You're trying to access a project you're not a member of or a project that does not exist.")
    else:
        # User is a member
        project = Project.objects.get(slug=slug)
        invites = Invitation.objects.filter(project=project)
        memberships = project.memberships.all()
        context = {
            'project':project,
            'invites':invites,
            'memberships':memberships,
            'userperm':project.memberships.get(user=request.user),
            'user':request.user,
            'admins':project.memberships.filter(is_owner=True).count(),
        }
        template = 'projects/project_settings.html'
        return render(request, template, context)

@login_required
def edit_project_settings(request, slug):
    """
    Only admin can access this view
    Allows the admin to edit the project information
    """
    # Try except to make sure the user is a member of this project
    try:
        ProjectMember.objects.get(user=request.user, project=Project.objects.get(slug=slug))
    except ObjectDoesNotExist:
        # User is not a member
        return HttpResponse("You're trying to access a project you're not a member of or a project that does not exist.")
    else:
        # User is a member,
        project = get_object_or_404(Project, slug=slug)
        # Access control, if not owner - access denied..
        if ProjectMember.objects.get(user=request.user, project=project).is_owner:
            # User has access
            form = forms.CreateProjectForm(request.POST or None, instance=project)
            if request.method == 'POST':
                # User submitted data
                if form.is_valid():
                    # form is valid - Save
                    form.save()
                    # slug could have been updated - make sure we redirect to the updated slug
                    slug = project.slug
                    return redirect('projects:settings', slug=slug)
            return render(request, 'projects/project_edit.html', {'form':form, 'project':project})
        else:
            # Access denied
            return HttpResponse("You don't have the permission to do this")

def edit_project_member(request, slug, pk):
    """
    This view is only available to the project admin.
    This view allows the admin to edit the details of a group member.
    """
    # Try except to make sure the user is a member of this project
    try:
        ProjectMember.objects.get(user=request.user, project=Project.objects.get(slug=slug))
    except ObjectDoesNotExist:
        # User is not a member
        return HttpResponse("You're trying to access a project you're not a member of or a project that does not exist.")
    else:
        # User is a member,
        user = User.objects.get(pk=pk)
        project = Project.objects.get(slug=slug)

        # Access control, if not owner - access denied..
        if ProjectMember.objects.get(user=request.user, project=project).is_owner:
            projectmember = ProjectMember.objects.get(user=user, project=project)
            if request.method == 'POST':
                # User submitted data
                form = forms.ProjectMemberForm(request.POST)
                if form.is_valid():
                    # Form is valid, reset user permission and set the new. save.
                    setattr(projectmember, 'is_owner', False)
                    setattr(projectmember, 'is_editor', False)
                    setattr(projectmember, 'is_reader', False)
                    setattr(projectmember, request.POST['permission'], True)
                    projectmember.save()
                    # Redirect the user to the project settings page
                    return redirect('projects:settings', slug=slug)

            # this is used to fill the form with accurate data.
            if projectmember.is_owner:
                permission = 'is_owner'
            elif projectmember.is_editor:
                permission = 'is_editor'
            else:
                permission = 'is_reader'
            form = forms.ProjectMemberForm(request.POST or None, initial={'permission':permission})
            context = {
                'form':form,
                'projectmember':projectmember,
                'project':project,
                'user':request.user,
                'admins':ProjectMember.objects.filter(project=project, is_owner=True).count()
            }
            return render(request, 'projects/project_member_form.html', context)
        else:
            # Access denied
            return HttpResponse("You don't have the permission to do this")

@login_required
def project_invite(request, slug):
    """
    This view is only available to the project admin.
    This view allows the admin to invite users to a project.
    """
    # Try except to make sure the user is a member of this project
    try:
        ProjectMember.objects.get(user=request.user, project=Project.objects.get(slug=slug))
    except ObjectDoesNotExist:
        # User is not a member
        return HttpResponse("You're trying to access a project you're not a member of or a project that does not exist.")
    else:
        # User is a member,
        project = Project.objects.get(slug=slug)

        # Access control, if not owner - access denied..
        if ProjectMember.objects.get(user=request.user, project=project).is_owner:
            # User has access
            context = {
                'project':project
            }

            if request.method == 'POST':
                # User submitted data
                form = forms.InviteForm(request.POST, project=project)
                if form.is_valid():
                    # form is valid, create invitation and save
                    inv = Invitation()
                    inv.sender = request.user
                    inv.project = project
                    inv.reciever = User.objects.get(email=request.POST['email'])
                    inv.message = request.POST['message']
                    setattr(inv, request.POST['permission'], True)
                    inv.save()
                    # Send user back to the project settings page
                    return redirect('projects:settings', slug=slug)

            form = forms.InviteForm(request.POST or None, initial={'permission': 'is_editor'},  project=project)
            context['form'] = form
            template = 'projects/project_invite.html'
            return render(request, template, context)
        else:
            # Access denied
            return HttpResponse("You don't have the permission to do this")

@login_required
def project_import_file(request, slug):
    """

projects/templates/projects/project_edit.html
{% extends "projects/project_base.html" %}
{% load material_form %}
{% block breadcrumb %}
<a href="{% url 'projects:all' %}" class="breadcrumb">My Projects</a>
<a href="{% url 'projects:single' slug=project.slug %}" class="breadcrumb">{{ project.project_title }}</a>
<a href="{% url 'projects:settings' slug=project.slug %}" class="breadcrumb">Settings</a>
<a href="{% url 'projects:edit' slug=project.slug %}" class="breadcrumb">Edit</a>

{% endblock %}
{% block project_content %}

<div class="row">
  <div class="col s12">
    <div class="card">
      <div class="card-content">
        <div class="row">
          <div class="col s12">
          <span class="card-title center"><h2>Update {{ project.project_title }}</h2></span>
            <form class="" action="{% url 'projects:edit' slug=project.slug %}" method="POST" id="projectForm">
              {% csrf_token %}
              {% form %}{% endform %}
              <div class="center-align">
                <button type="submit" name="_submit" class="btn indigo btn-large waves waves-effect">Update Project</button>
              </div>
            </form>

          </div>
        </div>
        <div class="card-action">
        </div>
      </div>
    </div>
  </div>
</div>



{% endblock %}

projects/templates/projects/project_list.html
{% extends "projects/project_base.html" %}
{% load static %}
{% block breadcrumb %}
<a href="{% url 'projects:all' %}" class="breadcrumb">My Projects</a>

{% endblock %}
{% block preproject %}

{% endblock %}

{% block project_content %}

<div class="row">
  <div class="col s12">
    <div class="card-panel">
      <div class="card-content">
        <div class="center-align">



            <span class="card-title"><h2>My Projects</h2></span>
            <p>Access your projects below or create a new one to get started!</p>
              <a href="{% url 'projects:create' %}" class="btn indigo btn-medium waves waves-effect">Create New Project</a>
            </div>
            <br>
            
          {% if invites %}
            <ul class="collection with-header">
              <li class="collection-header grey lighten-2"><h4>Project Invitations</h4></li>
              {% for invite in invites %}
                <li class="collection-item">
                  <div>
                  <h5>{{ invite.project.project_title.upper }}</h5>
                    <span class="new badge indigo lighten-2" data-badge-caption="Member{{ invite.project.members.count|pluralize }}">{{ invite.project.members.count }}</span>
                    <span class="new badge indigo lighten-2" data-badge-caption="Record{{ invite.project.records.count|pluralize }}">{{ invite.project.records.count }}</span>
                    <span class="new badge amber darken-2">   </span>
                    <p>{{ invite.sender.first_name }} {{ invite.sender.last_name }}
                    sent you this invite!</p>
                    <p>{{ invite.message }}</p>
                    <span class="">
                      <a class="btn btn-small waves-effect waves-light grey " href="{% url 'projects:decline' slug=invite.project.slug %}">
                        <i class="material-icons left">clear</i>
                        decline
                      </a>
                      <a class="btn waves-effect waves-light indigo darken-3" href="{% url 'projects:accept' slug=invite.project.slug %}">
                        <i class="material-icons left">done</i>
                        Accept
                      </a>

                    </span>
                  </div></li>
              {% endfor %}
            </ul>
            {% endif %}


<!-- ############################################### -->
{% if projects %}
              <ul class="collection with-header">
                <li class="collection-header grey lighten-2"><h4>Projects</h4></li>
                {% for project in projects %}
                  <a href="{% url 'projects:single' slug=project.slug %}" class="collection-item indigo-text">
                    <div>
                      <span class="new badge indigo lighten-2" data-badge-caption="Member{{ project.members.count|pluralize }}">{{ project.members.count }}</span>
                      <span class="new badge indigo lighten-2" data-badge-caption="Record{{ project.records.count|pluralize }}">{{ project.records.count }}</span>

                      <h5>{{ project.project_title.upper }}</h5>

                      <p>{{ project.description|truncatechars:100 }}</p>

                    </div></li></a>
                {% endfor %}
              </ul>
{% endif %}
      </div>
    </div>
  </div>
</div>
{% endblock %}

projects/templates/projects/project_member_form.html
{% extends "projects/project_base.html" %}
{% load material_form %}
{% block breadcrumb %}
<a href="{% url 'projects:all' %}" class="breadcrumb">My Projects</a>
<a href="{% url 'projects:single' slug=project.slug %}" class="breadcrumb">{{ projectmember.project.project_title }}</a>
<a href="{% url 'projects:settings' slug=project.slug %}" class="breadcrumb">Settings</a>
<a href="{% url 'projects:editperm' slug=project.slug pk=projectmember.user.pk %}" class="breadcrumb">Edit Permission</a>
{% endblock %}

{% block project_content %}

<div class="row">
  <div class="col s12">
    <div class="card">
      <div class="card-content">
        <div class="row">
          <div class="col s12">
            <h3 class="center">{{ projectmember.user.first_name }} {{ projectmember.user.last_name }}</h3>
            <div class="row">
              <div class="col s6 offset-s3">
                {% if user == projectmember.user %}
                  {% if admins > 1 %}
                  <form class="" action="{% url 'projects:editperm' slug=project.slug pk=projectmember.user.pk %}" method="POST">
                    {% csrf_token %}
                    {% form form=form %} {% endform %}
                    <div class="center-align">
                      <button type="submit" name="_submit" class="btn indigo waves-light waves-effect">save changes</button>
                    </div>
                  </form>
                  {% else %}
                    To change your own permission first make sure to promote another project admin
                  {% endif %}
                  {% else %}
                  <form class="" action="{% url 'projects:editperm' slug=project.slug pk=projectmember.user.pk %}" method="POST">
                    {% csrf_token %}
                    {% form form=form %} {% endform %}
                    <div class="center-align">
                      <button type="submit" name="_submit" class="btn indigo waves-light waves-effect">save changes</button>
                    </div>
                  </form>
                {% endif %}
              </div>
            </div>
            {% if user != projectmember.user %}
            <a class="btn waves-effect red darken-3 waves-light right" href="{% url 'projects:delete-member' slug=project.slug pk=projectmember.user.pk %}"><i class="material-icons left">delete</i>Remove member</a>
            {% endif %}
            <a class="waves-effect btn-flat waves-grey blue-grey-text waves-light left" href="{% url 'projects:settings' slug=project.slug %}">Back</a>
          </div>
        </div>
        <div class="card-action">

        </div>
      </div>
    </div>
  </div>
</div>


{% endblock %}

projects/templates/projects/project_settings.html
{% extends "projects/project_base.html" %}
{% load static %}
{% block breadcrumb %}
<a href="{% url 'projects:all' %}" class="breadcrumb">My Projects</a>
<a href="{% url 'projects:single' slug=project.slug %}" class="breadcrumb">{{ project.project_title }}</a>
<a href="{% url 'projects:settings' slug=project.slug %}" class="breadcrumb">Settings</a>
{% endblock %}
{% block project_content %}




<div class="row">
  <div class="col s12">
    <div class="card">
      <div class="card-content">
        <div class="row">
          <div class="col s12">

                  <h2 class="center">{{ project.project_title }}</h2>
                  <h6 class="center">{{ project.description }}</h6><br>
                  <div class="right-align">
                    {% if userperm.is_owner %}
                    <a class="btn waves-effect btn-medium waves-light indigo" href="{% url 'projects:edit' slug=project.slug %}">
                      <i class="material-icons left">edit</i>
                      Edit Description
                    </a>
                    {% endif %}
                  </div>

                  <hr>
                  <ul class="collection with-header">

                    <li class="collection-header">

                        <h4>Project Members</h4>

                      </li>
                    {% for member in memberships %}
                      <li class="collection-item avatar">

                        <img src="{% static 'images/usericon.svg' %}" alt="avatar" class="circle"></img>
                        <span class="title">{{ member.user.first_name }} {{ member.user.last_name }}</span>
                        <p>{{ member.user.email }}<br>
                        {% if userperm.is_owner or member.user == user %}
                          {% if member.is_owner %}
                            Admin
                          {% elif member.is_editor %}
                            Read&write
                          {% elif member.is_reader %}
                            ReadOnly
                          {% endif %}
                        {% endif %}

                        </p>
                        {% if userperm.is_owner %}
                        <span class="secondary-content">
                          <a href="{% url 'projects:editperm' slug=project.slug pk=member.user.pk %}" ><i class="material-icons">edit</i></a>
                          {% if user != member.user %}

                            <a href="{% url 'projects:delete-member' slug=project.slug pk=member.pk %}"><i class="material-icons">delete</i></a>
                          {% endif %}
                        </span>
                          {% endif %}
                      </li>
                    {% endfor %}
                  </ul>
                {% if userperm.is_owner %}
                  {% if invites %}
                  <ul class="collection with-header">

                    <li class="collection-header">
                        <h4>Pending Invitations</h4>

                      </li>
                    {% for invite in invites %}
                    <li class="collection-item">
                      <div>
                        <strong>{{ invite.reciever.first_name }} {{ invite.reciever.last_name }}</strong>
                        has been invited by   <strong>{{ invite.sender.first_name }} {{ invite.sender.last_name }}</strong>
                        <a href="{% url 'projects:withdraw' slug=invite.project.slug pk=invite.pk %}" class="secondary-content"><i class="material-icons">delete</i></a>
                      </div>
                    </li>

                    {% endfor %}
                  </ul>
                  {% endif %}
                  <div class="center-align">
                    <a  href="{% url 'projects:invite' slug=project.slug %}"
                        class="btn btn-medium indigo waves-effect waves-light">
                        <i class="material-icons left">person_add</i> Invite User to Collaborate</a>

                  </div>
                  {% endif %}


          </div>
        </div>
        <div class="card-action">
          <div class="right-align">
            {% if memberships.count > 1 and admins > 1 or not userperm.is_owner %}
            <a class="btn waves-effect waves-light orange" href="#leave_project{{ project.pk }}">
              <i class="material-icons left">block</i>
              Leave Project
            </a>
            {% endif %}
            {% if userperm.is_owner %}
            <a class="btn waves-effect waves-light red darken-3" href="#delete_project{{ project.pk }}">
              <i class="material-icons left">delete</i>
              Delete Project
            </a>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>
</div>



<!-- MODALS -->

<div id="leave_project{{ project.pk }}" class="modal">
  <div class="modal-content">
    <h4 class="center-align">Are you sure you want to leave '{{ project.project_title }}'</h4>
    <p class="center-align">
      Leaving this project means that you lose all access to it.
      <br> To re-attain access you need to be re-invited.
    </p>
  </div>
  <div class="modal-footer">
    <div class="modal-action right-align">
      <a href="" class="modal-close btn-flat waves-effect waves-blue grey-text">Cancel</a>
      <a href="{% url 'projects:leave' slug=project.slug %}" class="modal-close btn-flat waves-effect waves-orange blue-grey-text">Leave project</a>
    </div>
  </div>
</div>

<div id="delete_project{{ project.pk }}" class="modal">
   <div class="modal-content">
     <h4 class="center-align">Are you sure you want to delete '{{ project.project_title }}'</h4>
     <p class="center-align">Deleting the project will also delete any records
     within the project. <br>This will delete the project for
     everyone that is a projectmember. <br> {% if memberships.count > 1 and admins > 1 %}To Delete
     the project locally; use the 'Leave' option.<br>{% endif %}
     Deleting this project can not be reversed.</p>
   </div>
   <div class="modal-footer">
    <div class="modal-action right-align">

      <a href="" class="modal-close btn-flat waves-effect waves-blue grey-text">Cancel</a>
      {% if memberships.count > 1 and admins > 1 %}
        <a href="{% url 'projects:leave' slug=project.slug %}" class="modal-close btn-flat waves-effect waves-orange blue-grey-text">Leave project</a>
      {% endif %}
      <a href="{% url 'projects:delete' slug=project.slug %}" class="modal-close btn-flat waves-effect waves-red blue-grey-text">Delete project</a>

    </div>
   </div>
 </div>


<script type="text/javascript" src="{% static 'js/modal.js' %}">

</script>
{% endblock %}