accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from . import forms

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html', form_class=forms.MyLoginForm),name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('my-profile/', views.account_detail, name='detail'),
    path('my-profile/delete/', views.delete_account, name='delete'),
]

mubm/urls.py
from django.contrib import admin
from django.urls import re_path, path, include
from . import views
from records import ajax_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('test/', views.TestPage.as_view(),name='test'),
    path('thanks/', views.ThanksPage.as_view(), name='thanks'),
    path('projects/', include('projects.urls', namespace='projects')),
]

projects/urls.py
from django.urls import path, re_path, include
from . import views

app_name = 'projects'


urlpatterns = [
    path('', views.list_projects, name='all'),
    path('new/', views.create_project ,name='create'),
    path('<slug:slug>/records/', include('records.urls', namespace='records')),
    path('<slug:slug>/', views.project_detail, name='single'),
    path('<slug:slug>/leave/', views.LeaveProject.as_view(),name='leave'),
    path('<slug:slug>/invite/', views.project_invite ,name='invite'),
    path('<slug:slug>/delete/', views.delete_project, name='delete'),
    path('<slug:slug>/settings/', views.project_settings, name='settings'),
    path('<slug:slug>/settings/update', views.edit_project_settings, name='edit'),
    path('<slug:slug>/accept-invite/', views.JoinProject.as_view(), name='accept'),
    path('<slug:slug>/decline-invite/', views.DeclineInvite.as_view(), name='decline'),
    path('<slug:slug>/withdraw-invite/<int:pk>', views.delete_invite, name='withdraw'),
    path('<slug:slug>/delete-member/<int:pk>', views.delete_member, name='delete-member'),
    path('<slug:slug>/import/', views.project_import_file, name='import'),
    path('<slug:slug>/export/', views.project_export_file, name='export'),
    path('<slug:slug>/<int:pk>/edit-perm/', views.edit_project_member, name='editperm'),

]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>
      {% block title_block %}

      {% endblock %}
    </title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    {% include 'material/includes/material_css.html' %}
   {% include 'material/includes/material_js.html' %}

      <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Import materialize.css-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/css/materialize.min.css">

    {% block head_block %}

    {% endblock %}
    <link rel="stylesheet" href="{% static 'css/master.css' %}">
  </head>
  <body class="grey lighten-3">

      {% if user.is_authenticated %} <!-- sidenav will only be present if user is logged in -->
        <div class="row">
        <!-- ################### -->

  <header>
    <ul class="sidenav sidenav-fixed side-nav">
      <li>
        <div class="user-view">
          <div class="background">
            <img src="{% static 'images/userview.jpg' %}" alt="">
          </div> <!-- close background -->
          <div class="user-img">



              <br><br><br><br>
          </div> <!-- close user-img -->
          <div class="section">
            <h5 class="white-text">{{ user.first_name }} {{ user.last_name }}</h5>
          </div> <!-- close section -->
        </div> <!-- close user view -->
      </li>
        <li><a href="{% url 'projects:all' %}">My Projects</a></li>
        <li><a href="{% url 'accounts:detail' %}">My Profile</a></li>
        <div class="section">
      <li><a href="#">Settings</a> </li>
      <li><a href="{% url 'accounts:logout' %}">Log out</a> </li>
        </div>
    </ul>
  </header>




  <div class="my-page">
    <!-- Navbar -->
    <div class="navbar-fixed">


      <nav class="blue-grey darken-2">
        <div class="nav-wrapper">
          <div class="row">
            <div class="col s12">
              <a href="{% url 'home' %}" class="brand-logo hide-on-med-and-down">Multi-User BibTeX Manager</a>

              <ul class="right">
                <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
              </ul>
            </div> <!-- close col -->
          </div> <!-- close row -->
        </div> <!-- close nav-wrapper -->
      </nav>
    </div>

          <div class="navbar-fixed">
            <nav class="blue-grey darken-2 hide-on-med-and-down">
              <div class="nav-wrapper">
                <div class="col s12">
                  <a href="{% url 'home' %}" class="breadcrumb">Home</a>
                    {% block breadcrumb %}{% endblock %}
                </div>
              </div>
            </nav>
          </div>
          <div class="row">
            <div class="col l11 m11">
            {% block content %}{% endblock %}
            </div>
          </div>
          </div>

            <!-- ################### -->

        </div> <!-- close row -->



      {% else %}
        <!-- Navbar -->
        <nav class="blue-grey darken-2">
          <div class="nav-wrapper">
            <div class="row">
              <div class="col s12">
                <a href="{% url 'home' %}" class="brand-logo center">Multi-User BibTeX Manager</a>
                <ul class="right hide-on-med-and-down">
                  <li><a href="{% url 'accounts:login' %}">Log In</a></li>
                  <li><a href="{% url 'accounts:signup' %}">Sign Up</a></li>
                </ul>
              </div> <!-- close col -->
            </div> <!-- close row -->
          </div> <!-- close nav-wrapper -->
        </nav>

        {% block content_account %}{% endblock %}
      {% endif %}


    <!--JavaScript at end of body for optimized loading-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/js/materialize.min.js"></script>



  </body>
</html>

templates/index.html
{% extends "base.html" %}

{% block title_block %}

{% endblock %}

{% block content %}
<div class="row">
  <div class="col s12">
    <div class="card-panel">
      <div class="card-content">
        <div class="center-align">
            <span class="card-title"><h3>Welcome to a free Multi-User BibTeX Manager</h3></span>
            <p>This website is currently being developed and as a result it may not be functioning properly. Please feel free to try it out but I would not recommend using it as your primary bibliography manager, yet ;).
<br> <br>
The website is currently being evaluated and documented and will have an official launch date later this year.
<br> <br>
If you have any questions or concerns please contact me at 2277194e@student.gla.ac.uk and I will get back to you as soon as possible.
<br> <br>
Best regards,
<br> <br>
Viktor Eriksson
</p>
        </div>
          <br>
        <div class="" style="height:400px">

        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block content_account %}
<div class="row">
  <div class="col s8 offset-s2">
    <div class="card-panel">
      <div class="card-content">
        <div class="center-align">
            <span class="card-title"><h3>Welcome to a free Multi-User BibTeX Manager</h3></span>
            </div>
            <p>This website is currently being developed and as a result it may not be functioning properly. Please feel free to try it out but I would not recommend using it as your primary bibliography manager, yet ;).
<br> <br>
The website is currently being evaluated and documented and will have an official launch date later this year.
<br> <br>
If you have any questions or concerns please <a href="mailto:2277194e@student.gla.ac.uk" target="_top">contact me</a> and I will get back to you as soon as possible.
<br> <br>
Best regards,
<br> <br>
Viktor Eriksson
</p>

          <br>
          Using this application you will be able to:
          <ul>
              <li><i class="material-icons">chevron_right</i>Add, Edit, Delete, View your BibTeX records</li>
              <li><i class="material-icons">chevron_right</i>Import bibliographies from file (currently supports .bib files)</li>
              <li><i class="material-icons">chevron_right</i>Export bibliographies to file (currently supports .bib files)</li>
              <li><i class="material-icons">chevron_right</i>filter, search and sort through big bibliographies</li>
              <li><i class="material-icons">chevron_right</i>Invite friends or collegues to work on your bibliography</li>
              <li><i class="material-icons">chevron_right</i>Give your collegues different level of access (ReadOnly / ReadWrite / Admin)</li>
          </ul>
          <br>
          <a href="{% url 'accounts:signup' %}">Sign up here</a>. If you wish to learn more about BibTeX visit <a href="http://www.bibtex.org/">www.bibtex.org</a>.
        <div class="" style="height:400px">

        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/test.html
{% extends "base.html" %}

{% block title_block %}

{% endblock %}

{% block content %}
  <h1>Testpage</h1>
  <h3>If you see this, it's working</h3>
{% endblock %}

templates/thanks.html
{% extends "base.html" %}

{% block title_block %}

{% endblock %}

{% block content_account %}
  <h1 class="center-align">Sad to see you go, come back soon!</h1>

{% endblock %}